@startuml "Sistema de Gestão de Manutenção"

header Engenharia de Software - Casos de Uso
title Diagrama de Casos de Uso - Manutenção Industrial

left to right direction

actor "Solicitante" as S
actor "Técnico" as T
actor "Gestor" as G

'O Gestor pode realizar tudo que o Solicitante faz
G -up-|> S

rectangle "Sistema de Gestão de Manutenção" {
    
    usecase "Abrir Ordem de Serviço" as UC01
    usecase "Cadastrar Equipamento" as UC_CAD_EQUIP
    
    usecase "Designar Técnico para OS" as UC02
    
    usecase "Atualizar Status da OS" as UC03
    
    usecase "Registrar Uso de Ferramenta" as UC04
    
    usecase "Consultar Histórico de Equipamento" as UC05
    
    usecase "Visualizar Dashboard de Métricas e Relatórios" as UC06
    
    usecase "Manter Usuários e Técnicos" as UC_MAN_USER

    UC01 <.. UC_CAD_EQUIP : <<extend>>
    UC04 ..> UC03 : <<extend>>
}

S --> UC01
S --> UC05

T --> UC03
T --> UC04
T --> UC05

G --> UC02
G --> UC05
G --> UC06
G --> UC_MAN_USER

@enduml